name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy-adk-agent:
    if: "contains(github.event.head_commit.message, '[adk-agent]') || !contains(github.event.head_commit.message, '[')"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL_ID }}/providers/${{ secrets.WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - run: gcloud builds submit ./services/adk-agent --tag "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/adk-agent-repo/adk-agent:${{ github.sha }}" --project=${{ vars.STAGING_PROJECT_ID }}
      - run: gcloud run deploy adk-agent --image "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/adk-agent-repo/adk-agent:${{ github.sha }}" --region ${{ vars.GCP_REGION }} --service-account "${{ vars.REPOSITORY_NAME }}-app-sa@${{ vars.STAGING_PROJECT_ID }}.iam.gserviceaccount.com" --project=${{ vars.STAGING_PROJECT_ID }}

  deploy-fastapi-backend:
    if: "contains(github.event.head_commit.message, '[fastapi-backend]') || !contains(github.event.head_commit.message, '[')"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL_ID }}/providers/${{ secrets.WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - run: gcloud builds submit ./services/fastapi-backend --tag "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/fastapi-backend-repo/fastapi-backend:${{ github.sha }}" --project=${{ vars.STAGING_PROJECT_ID }}
      - run: gcloud run deploy fastapi-backend --image "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/fastapi-backend-repo/fastapi-backend:${{ github.sha }}" --region ${{ vars.GCP_REGION }} --service-account "${{ vars.REPOSITORY_NAME }}-app-sa@${{ vars.STAGING_PROJECT_ID }}.iam.gserviceaccount.com" --project=${{ vars.STAGING_PROJECT_ID }}

  deploy-nextjs-frontend:
    if: "contains(github.event.head_commit.message, '[nextjs-frontend]') || !contains(github.event.head_commit.message, '[')"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL_ID }}/providers/${{ secrets.WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
      - run: gcloud builds submit ./services/nextjs-frontend --tag "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/nextjs-frontend-repo/nextjs-frontend:${{ github.sha }}" --project=${{ vars.STAGING_PROJECT_ID }}
      - run: gcloud run deploy nextjs-frontend --image "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.STAGING_PROJECT_ID }}/nextjs-frontend-repo/nextjs-frontend:${{ github.sha }}" --region ${{ vars.GCP_REGION }} --service-account "${{ vars.REPOSITORY_NAME }}-app-sa@${{ vars.STAGING_PROJECT_ID }}.iam.gserviceaccount.com" --project=${{ vars.STAGING_PROJECT_ID }}
